In [45]:
import sys
import os
sys.path.append(os.path.join(os.pardir, 'dataset'))
import mnist
import numpy as np

In [13]:
# 4.2.1 2乗和誤差
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

assert len(y) == len(t) == 10
assert np.argmax(y) == np.argmax(t) == 2


In [14]:
# 2乗和誤差式
def mean_squared_error(y, t):
    # 全然関係ないが 1/2 とは書かずに0.5と書くの？
    return 0.5 * np.sum((y - t) ** 2)


In [27]:
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

# 「2」の確率が最も高い場合
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
assert np.argmax(y) == np.argmax(t) == 2
assert mean_squared_error(np.array(y), np.array(t)) == 0.09750000000000003

y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]
assert np.argmax(y) == 7
assert mean_squared_error(np.array(y), np.array(t)) == 0.5975

# 数字が小さいのは最初の例なので、最初のほうが教師データに適合している

In [34]:
# 4.2.2 交差エントロピー誤差
def cross_entropy_error(y: np.ndarray, t: np.ndarray):
    # np.log(0) とならないように微小な値で調整
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

In [40]:
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

# 「2」の確率が最も高い場合
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
assert np.argmax(y) == np.argmax(t) == 2
assert cross_entropy_error(np.array(y), np.array(t)) == 0.510825457099338

y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]
assert np.argmax(y) == 7
assert cross_entropy_error(np.array(y), np.array(t)) == 2.302584092994546

# 数字が小さいのは最初の例なので、最初のほうが教師データに適合している
# これまでの話と一致

In [54]:
# 4.2.3 ミニバッチ学習
(x_train, t_train), (x_test, t_test) = mnist.load_mnist(normalize=True, one_hot_label=True)
assert x_train.shape == (60000, 784)
assert t_train.shape == (60000, 10)

train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)
x_batch = x_train[batch_mask]
t_batch = t_train[batch_mask]
# ランダムで10個選択されている
print(x_batch)
print(t_batch)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [56]:
# np.random.choice で指定の数からランダムに取得可能
np.random.choice(60000, 10)

array([53724, 10286, 35978, 11010,  7042, 58523, 39449, 19751, 22596,
       20654])